[build]
  base = "."
  command = "pnpm install && pnpm --filter @aurora-mp/docs build"
  publish = "docs/build"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"
  NETLIFY_USE_NIX = "false"
  PNPM_HOME = "/opt/buildhome/.pnpm"
  NPM_CONFIG_USERCONFIG = "/dev/null"
  NETLIFY_USE_PNPM = "true"
  PATH = "/opt/build/repo/node_modules/.bin:/opt/buildhome/.pnpm:$PATH"