[build]
  base = "."
  command = "pnpm install && pnpm --filter @aurora-mp/docs build"
  publish = "docs/build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_PNPM = "true"
  NETLIFY_USE_NIX = "false"
