packages:
  - docs
  - packages/*
  - packages/platforms/ragemp/**
  - packages/platforms/fivem/**
  - tests/ragemp/**
  - tests/fivem/**
  - tests/webview/**

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver
