packages:
  - docs
  - packages/*
  #- packages/platforms/altv/**
  - packages/platforms/ragemp/**
  #- packages/platforms/fivem/**
  #- tests/ragemp
  #- tests/fivem/**
  #- tests/webview/*
  #- armonia/**

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver
